apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-app
  namespace: default
  labels:
    app: node-hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-app
  template:
    metadata:
      labels:
        app: node-hello-app
    spec:
      containers:
      - name: node-app
        image: node:18-alpine
        command: 
        - node
        - -e
        - |
          const http = require('http');
          const server = http.createServer((req, res) => {
            res.writeHead(200, {'Content-Type': 'text/plain'});
            res.end('Hello World from Node.js Web Server!');
          });
          server.listen(3000, () => console.log('Server running on port 3000'));
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
