apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
  namespace: default
  labels:
    app: node-hello-app
spec:
  selector:
    app: node-hello-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
